<a href="https://colab.research.google.com/github/chrisnjw/Tensorflow_playground/blob/main/00_pytorch_playground_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


### Intoduction to Tensors

In [2]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data`

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8333, 0.9651, 0.6022, 0.9516],
        [0.6439, 0.9228, 0.8778, 0.1712],
        [0.5974, 0.3450, 0.2575, 0.4798]])

In [15]:
random_tensor.ndim

2

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros.dtype

torch.float32

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(4,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [21]:
# Using torch.range()
# If deprecated message is shown, use torch.arange()
torch.range(0, 10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  This is separate from the ipykernel package so we can avoid doing imports until


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
one_to_ten = torch.arange(start=1, end=11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor dataypes

**Note:** Tensor dataypes is one of the 3 big errors you will run into with pytorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # Datatype of the tensors
                               device=None, # Device the tensor is on
                               requires_grad=False) # Whether gradients tracking is necessary
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors (Tensors attribute)

Tensors not right dataype - to get datatype from a tensor, can use `tensor.dtype`

Tensors not right shape - to get shape from a tensor, can use `tensor.shape`

Tensors not on the right device - to get device from a tensor, can use tensor.device

In [28]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2174, 0.4557, 0.5516, 0.5004],
        [0.6651, 0.6882, 0.3789, 0.9886],
        [0.5753, 0.2027, 0.6272, 0.7860]])

In [29]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2174, 0.4557, 0.5516, 0.5004],
        [0.6651, 0.6882, 0.3789, 0.9886],
        [0.5753, 0.2027, 0.6272, 0.7860]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [30]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [31]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [32]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication

In [33]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.61 ms, sys: 0 ns, total: 1.61 ms
Wall time: 1.7 ms


In [34]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 3.35 ms, sys: 0 ns, total: 3.35 ms
Wall time: 16.1 ms


tensor(14)

### Common error in deep learning: shape error

There are two main rules that performing matrix multiplication needs to satisfy:

1. The inner dimension must match
2. The resulting matrix has the shape of the outer dimensions

In [35]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7, 10], [8, 11],
                        [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is same as torch.matmul
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

To fix our tensor shape issues, can manipulate the shape of one of the tensor using **transpose**

**transpose** switches the axes or dimensions of a given tensor

In [36]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [37]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [39]:
# Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

### Finding the positional min and max

In [40]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target
# occur
x.argmin()

tensor(0)

In [41]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [43]:
# Creating a tensor
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [44]:
# Add an extra dimension
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]), torch.Size([5, 2]))

In [45]:
# Change the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [46]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [47]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [48]:
# torch.squeeze() - remove all the single dimensions from a target tensor
x_reshaped

tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [49]:
x_reshaped.shape

torch.Size([5, 2])

In [50]:
x_reshaped.squeeze()

tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [51]:
x_reshaped.squeeze().shape

torch.Size([5, 2])

In [52]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 ->1, 1->2, 2->0

In [53]:
print(f"Previous shape : {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape : torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [54]:
# Create a tensor

import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [55]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [57]:
# Indexing on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [58]:
# Using ":" to select "all" of a target dimension
x[:, 1]

tensor([[4, 5, 6]])

In [59]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [60]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2md dimension
x[:, 1, 1]

tensor([5])

In [61]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [62]:
# Index on x to return 9
x[:, 2, 2]

tensor([9])

In [63]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a poplar scientifice Python numerical computing library.

Therefore, PyTorch has functionality to interact with it

* Data in Numpy, want in PyTorch tensor ->`torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> torch.Tensor.numpy()

In [64]:
# Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [65]:
array.dtype

dtype('float64')

In [66]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [67]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## reproducibility (trying to take random out of random)

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data `

To reduce the randomness in neural netowrks and PyTorch comes the concept of a **random seed**.
- Essentially, random seed dies is "flavour" the randomness

In [68]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9246, 0.0928, 0.4751, 0.7579],
        [0.5119, 0.0056, 0.2098, 0.0782],
        [0.1886, 0.3559, 0.2892, 0.0171]])
tensor([[0.1192, 0.3078, 0.0069, 0.3672],
        [0.6686, 0.5833, 0.5153, 0.6580],
        [0.4760, 0.6797, 0.5988, 0.2716]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [69]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Exercises

In [82]:
x = torch.rand(7, 7)
x

tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018],
        [0.9497, 0.6666, 0.9811, 0.0874, 0.0041, 0.1088, 0.1637],
        [0.7025, 0.6790, 0.9155, 0.2418, 0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524, 0.6057],
        [0.3725, 0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313]])

In [83]:
y = torch.rand(1, 7)
y

tensor([[0.3227, 0.0162, 0.2137, 0.6249, 0.4340, 0.1371, 0.5117]])

In [86]:
z = torch.matmul(x, y.T)
z, z.shape

(tensor([[1.0466],
         [1.0884],
         [0.9919],
         [0.6820],
         [0.9108],
         [1.0100],
         [0.8004]]), torch.Size([7, 1]))

In [87]:
# Setting manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7,7))
Y = torch.rand(size=(1,7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

In [88]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

In [89]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

Device: cpu


In [90]:
# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]), tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [91]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [92]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)

max, min

(tensor(0.5617), tensor(0.3647))

In [93]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3), tensor(0))

In [94]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
