<a href="https://colab.research.google.com/github/chrisnjw/Tensorflow_playground/blob/main/Exercises_tensorflow_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 00. TensorFlow Fundamental Exercises

In [21]:
import tensorflow as tf

In [22]:
# Creating a scalar (described by magnitude only)
scalar = tf.constant(8)
print(scalar)

tf.Tensor(8, shape=(), dtype=int32)


In [23]:
# Creating a vector (described by both magnitude and direction)
vector = tf.constant([1, 2, 3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [24]:
# Creating a matrix 
matrix = tf.constant([[1, 2],
                      [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [25]:
# Creating a tensor
tensor = tf.constant([[[10, 9, 8],
                       [1,2, 4],
                       [8, 4, 2]
                        ],
                       [[10, 9, 8],
                        [1,2, 4],
                        [8,4,2]
                        ]
                       ])
print(tensor)

tf.Tensor(
[[[10  9  8]
  [ 1  2  4]
  [ 8  4  2]]

 [[10  9  8]
  [ 1  2  4]
  [ 8  4  2]]], shape=(2, 3, 3), dtype=int32)


In [26]:
# Finding the shape, rank and size
print('Shape of tensor {shape_s}'.format(shape_s = tensor.shape))

Shape of tensor (2, 3, 3)


In [27]:
# Finding the rank (all the elements) of tensor
print(f'The rank of the tensor: {tf.size(tensor)}')

The rank of the tensor: 18


In [28]:
# Finding the rank of the tensor
print("Rank of the tensor: {tensor_rank}".format(tensor_rank = tf.rank(tensor)))

Rank of the tensor: 3


In [29]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300]
# Set seed
tf.random.set_seed(42)

# Setting up the shape
tensor_1 = tf.random.uniform(shape=(5, 300))
tensor_2 = tf.random.uniform(shape=(5,300))

tensor_1, tensor_1.shape, tensor_2, tensor_2.shape

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 TensorShape([5, 300]),
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.828

In [30]:
# Multiply the two tensor
print('Shape before the matrix multiplication')
print(tensor_1.shape)
print(tensor_2.shape)

Shape before the matrix multiplication
(5, 300)
(5, 300)


In [31]:
resultant_vector = tf.linalg.matmul(tensor_1, tf.transpose(tensor_2))
print("After multiplying the resultant vector is : {}".format(resultant_vector))
print("Resultant vector shape: {}".format(resultant_vector.shape))

After multiplying the resultant vector is : [[80.33344  73.40498  77.15962  73.98368  80.90053 ]
 [75.146355 68.80437  74.24302  71.841835 75.60206 ]
 [79.7594   75.644554 77.797585 74.74873  80.559845]
 [75.085266 69.06406  74.307755 72.27616  76.05668 ]
 [85.056885 74.266266 78.00687  74.88678  83.13418 ]]
Resultant vector shape: (5, 5)


In [32]:
# Multiply using tensordot
tf.tensordot(tensor_1, tf.transpose(tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33344 , 73.40498 , 77.15962 , 73.98368 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.085266, 69.06406 , 74.307755, 72.27616 , 76.05668 ],
       [85.056885, 74.266266, 78.00687 , 74.88678 , 83.13418 ]],
      dtype=float32)>

In [33]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
big_tensor = tf.random.uniform(shape = [224, 224, 3], minval=0, maxval=1)

big_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

In [35]:
# Finding the minimum value of the tensor
minimum = tf.math.reduce_min(big_tensor)
print("The minimum value is : {}".format(minimum))

The minimum value is : 2.384185791015625e-07


In [36]:
# Finding the maximum value of the tensor
maximum = tf.math.reduce_max(big_tensor)
print("The maximum value is : {}".format(maximum))

The maximum value is : 0.999991774559021


In [39]:
# Creating a tensor with random value before squeezing it to change the shape to 
# [224, 224, 3]

unsqueezed_tensor = tf.random.Generator.from_seed(42)
unsqueezed_tensor = unsqueezed_tensor.normal(shape = (1, 224, 224, 3))

# Before squeezing
print(f'The shape after squeezing : {unsqueezed_tensor.shape}')

The shape after squeezing : (1, 224, 224, 3)


In [40]:
# After squeezing 
squeezed_tensor = tf.squeeze(unsqueezed_tensor)
print('The shape after squeezing: {}'.format(squeezed_tensor.shape))

The shape after squeezing: (224, 224, 3)


# Create a tensor with shape [10] and finding the index which has the maximum value

In [41]:
ten_tensor = tf.constant([2, 3, 4, 5, 6, 9, -1.1, 8, 10, 9])

# Finding the index where value is maximum
max_value = tf.math.argmax(ten_tensor)

print(f'The indices where the value is maximum : {max_value}')
print("The maximum value was {}".format(ten_tensor[max_value]))

The indices where the value is maximum : 8
The maximum value was 10.0


In [42]:
# One-hot encode the tensor (Representation of categorical variable as binary vectors)

# 1. Need to cast first
tf.cast(ten_tensor, dtype=tf.int32)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 2,  3,  4,  5,  6,  9, -1,  8, 10,  9], dtype=int32)>

In [43]:
# One hot encoding the tensor of shape 10
tf.one_hot(tf.cast(ten_tensor, dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [44]:
gro_tensor = tf.constant([[[10, 9, 8],
                       [1,2, 4],
                       [8, 4, 2]
                        ],
                       [[10, 9, 8],
                        [1,2, 4],
                        [8,4,2]
                        ]
                       ])

In [45]:
gro_tensor.shape

TensorShape([2, 3, 3])

In [50]:
month = tf.constant([[[1, 2, 3],
         [4,5,6],
         ],
        [[7, 8, 9],
         [3, 9, 8]],
         [[10, 8, 9],
         [7, 11, 8]]
                ] )


In [51]:
tf.tensordot(gro_tensor, month, axes=1)

<tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[153, 156, 183],
         [123, 219, 196]],

        [[ 55,  50,  57],
         [ 38,  67,  54]],

        [[ 56,  64,  78],
         [ 58,  98,  96]]],


       [[[153, 156, 183],
         [123, 219, 196]],

        [[ 55,  50,  57],
         [ 38,  67,  54]],

        [[ 56,  64,  78],
         [ 58,  98,  96]]]], dtype=int32)>